apiVersion: v1
kind: PersistentVolumeClaim #claim the created volume
metadata:
  name: jenkins-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
